# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:

  peertube:
    image: chocobozzz/peertube:v7.2.3-bookworm
    env_file:
      - .env
    ports:
     - '${SERVER_PORT}:9000'
    volumes:
      - ${DATA_DIR}/data:/data
      - ${DATA_DIR}/config:/config
    depends_on:
      - postgres
      - redis
    restart: "always"
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: '1.5G'

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ${DATA_DIR}/redis:/data
    restart: "always"